#!/bin/bash
set -e;

# n8n init

if [ -n "${POSTGRES_N8N_USER:-}" ] && [ -n "${POSTGRES_N8N_PASSWORD:-}" ]; then
    if ! psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -tc "SELECT 1 FROM pg_database WHERE datname = '${POSTGRES_N8N_DB}'" | grep -q 1; then
        psql -U "$POSTGRES_USER" -c "CREATE DATABASE ${POSTGRES_N8N_DB}"
    fi 
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname ${POSTGRES_N8N_DB} <<-EOSQL
		CREATE USER ${POSTGRES_N8N_USER} WITH PASSWORD '${POSTGRES_N8N_PASSWORD}';
		GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_N8N_DB} TO ${POSTGRES_N8N_USER};
		GRANT CREATE ON SCHEMA public TO ${POSTGRES_N8N_USER};
	EOSQL
else
	echo "SETUP INFO: No Environment variables given!"
fi


# Langfuse init

if [ -n "${LANGFUSE_DATABASE_USERNAME:-}" ] && [ -n "${LANGFUSE_DATABASE_PASSWORD:-}" ]; then
    if ! psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -tc "SELECT 1 FROM pg_database WHERE datname = '${LANGFUSE_DATABASE_NAME}'" | grep -q 1; then
        psql -U "$POSTGRES_USER" -c "CREATE DATABASE ${LANGFUSE_DATABASE_NAME}"
    fi 
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname ${LANGFUSE_DATABASE_NAME} <<-EOSQL
		CREATE USER ${LANGFUSE_DATABASE_USERNAME} WITH PASSWORD '${LANGFUSE_DATABASE_PASSWORD}';
		GRANT ALL PRIVILEGES ON DATABASE ${LANGFUSE_DATABASE_NAME} TO ${LANGFUSE_DATABASE_USERNAME};
		GRANT CREATE ON SCHEMA public TO ${LANGFUSE_DATABASE_USERNAME};
	EOSQL
else
	echo "SETUP INFO: No Environment variables given!"
fi


# LiteLLM init

if [ -n "${POSTGRES_LITELLM_USER:-}" ] && [ -n "${POSTGRES_LITELLM_PASSWORD:-}" ]; then
    if ! psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -tc "SELECT 1 FROM pg_database WHERE datname = '${POSTGRES_LITELLM_DB}'" | grep -q 1; then
        psql -U "$POSTGRES_USER" -c "CREATE DATABASE ${POSTGRES_LITELLM_DB}"
    fi 
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname ${POSTGRES_LITELLM_DB} <<-EOSQL
		CREATE USER ${POSTGRES_LITELLM_USER} WITH PASSWORD '${POSTGRES_LITELLM_PASSWORD}';
		GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_LITELLM_DB} TO ${POSTGRES_LITELLM_USER};
		GRANT CREATE ON SCHEMA public TO ${POSTGRES_LITELLM_USER};
	EOSQL
else
	echo "SETUP INFO: No Environment variables given!"
fi

# OpenWeb init

if [ -n "${POSTGRES_OPENWEBUI_USER:-}" ] && [ -n "${POSTGRES_OPENWEBUI_PASSWORD:-}" ]; then
    if ! psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -tc "SELECT 1 FROM pg_database WHERE datname = '${POSTGRES_OPENWEBUI_DB}'" | grep -q 1; then
        psql -U "$POSTGRES_USER" -c "CREATE DATABASE ${POSTGRES_OPENWEBUI_DB}"
    fi 
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname ${POSTGRES_OPENWEBUI_DB} <<-EOSQL
		CREATE USER ${POSTGRES_OPENWEBUI_USER} WITH PASSWORD '${POSTGRES_OPENWEBUI_PASSWORD}';
		GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_OPENWEBUI_DB} TO ${POSTGRES_OPENWEBUI_USER};
		GRANT CREATE ON SCHEMA public TO ${POSTGRES_OPENWEBUI_USER};
	EOSQL
else
	echo "SETUP INFO: No Environment variables given!"
fi